DROP TABLE IF EXISTS SUSTABLE;
CREATE TABLE SUSTABLE (
   -- id INT NOT NULL,
    id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 0) PRIMARY KEY,
    question1 INT NOT NULL,
    question2 INT NOT NULL,
    question3 INT NOT NULL,
    question4 INT NOT NULL,
    question5 INT NOT NULL,
    question6 INT NOT NULL,
    question7 INT NOT NULL,
    question8 INT NOT NULL,
    question9 INT NOT NULL,
    question10 INT NOT NULL
);